export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_USER = 'SET_USER';

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSE_NAMES_SUCCESS = 'LOAD_COURSE_NAMES_SUCCESS';

export const LOAD_FOLDERS_SUCCESS = 'LOAD_FOLDERS_SUCCESS';

export const SELECT_COURSE = 'SELECT_COURSE';
export const SELECT_FOLDER = 'SELECT_FOLDER';

export const SEARCH_RESPONSE_SUCCESS = 'SEARCH_RESPONSE_SUCCESS';

export const SEARCH_MODAL = 'SEARCH_MODAL';
export const FOLDER_MODAL = 'FOLDER_MODAL';
export const CLOSE_SEARCH_MODAL = 'CLOSE_SEARCH_MODAL';
export const CLOSE_FOLDER_MODAL = 'CLOSE_FOLDER_MODAL';

export const SWITCH_TABS = 'SWITCH_TABS';
export const SWITCH_CHAPTER_TABS = 'SWITCH_CHAPTER_TABS';

export const LOAD_CHAPTER_VERSIONS_SUCCESS = 'LOAD_CHAPTER_VERSIONS_SUCCESS';
export const LOAD_VERSION_FILES_SUCCESS = 'LOAD_VERSION_FILES_SUCCESS';

export const CHANGE_CURRENT_VERSION_FILES_SUCCESS = 'CHANGE_CURRENT_VERSION_FILES_SUCCESS';
export const CHANGE_CURRENT_VERSION_SUCCESS = 'CHANGE_CURRENT_VERSION_SUCCESS';

export const LOAD_PROFESSOR_CHAPTERS_SUCCESS = 'LOAD_PROFESSOR_CHAPTERS_SUCCESS';
export const LOAD_PROFESSOR_COURSES_SUCCESS = 'LOAD_PROFESSOR_COURSES_SUCCESS';

export const LOAD_COURSE_BY_ID_SUCCESS = 'LOAD_COURSE_BY_ID_SUCCESS';

export const CHANGE_ADD_CHAPTER_TAB = 'CHANGE_ADD_CHAPTER_TAB';

export const SEARCH_CHAPTERS_SUCCESS = 'SEARCH_CHAPTERS_SUCCESS';

export const LOAD_CURRENT_CHAPTER_SUCCESS = 'LOAD_CURRENT_CHAPTER_SUCCESS';

export const ADD_UPLOAD_FILE_SUCCESS = 'ADD_UPLOAD_FILE_SUCCESS';
