export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_USER = 'SET_USER';

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSE_NAMES_SUCCESS = 'LOAD_COURSE_NAMES_SUCCESS';

export const LOAD_FOLDERS_SUCCESS = 'LOAD_FOLDERS_SUCCESS';

export const SEARCH_MODAL = 'SEARCH_MODAL';
export const CLOSE_SEARCH_MODAL = 'CLOSE_SEARCH_MODAL';
export const CLOSE_FOLDER_MODAL = 'CLOSE_FOLDER_MODAL';
export const FOLDER_MODAL = 'FOLDER_MODAL';

export const SWITCH_TABS = 'SWITCH_TABS';

export const SEARCH_RESPONSE_SUCCESS = 'SEARCH_RESPONSE_SUCCESS';
