export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_USER = 'SET_USER';

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSE_NAMES_SUCCESS = 'LOAD_COURSE_NAMES_SUCCESS';

export const LOAD_FOLDERS_SUCCESS = 'LOAD_FOLDERS_SUCCESS';

export const SELECT_COURSE = 'SELECT_COURSE';
export const SELECT_FOLDER = 'SELECT_FOLDER';

export const SEARCH_MODAL = 'SEARCH_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const SWITCH_TABS = 'SWITCH_TABS';
export const SWITCH_CHAPTER_TABS = 'SWITCH_CHAPTER_TABS';
